name: HASH
favicon: null
layout_spectrum: 0.32432
typography_spectrum: 0.68116
title: HASH Official
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d5cf'
    - '#afb0aa'
    - '#040314'
    - '#652c20'
    - '#935a38'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
