name: HASH
favicon: null
layout_spectrum: 0.32432
typography_spectrum: 0.68116
title: HASH Official
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8d0000'
    - '#004d97'
    - '#b1ac02'
    - '#01c3d4'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.6596007400657982
  rhythmicContrast: 0.9358467187266797
purpose: []
