title: HASH Official
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5977443
  brandStrength: 0.625
  lightness: 0.5687433
  brandColors:
    - '#d4d5cf'
    - '#afb0aa'
    - '#040314'
    - '#652c20'
    - '#935a38'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: HASH
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.68116
layout_spectrum: 0.32432
